let csrf='',role='';
async function api(u,o={}){let r=await fetch(u,o),j=await r.json();if(!r.ok)throw Error(j.message||'حدث خطأ');return j}
async function login(){try{let j=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u.value,password:p.value})});csrf=j.csrf;role=j.user.role;login.hidden=true;app.hidden=false;who.textContent=j.user.username+' | '+j.user.role;loadAll()}catch(e){err.textContent=e.message}}
async function loadAll(){loadToday();loadBookings();loadServices();loadNews();loadStats()}
async function loadToday(){try{let d=await api('/api/admin/today');todayRows.innerHTML=d.map(x=>`<div class="row"><b>${x.appointment_time}</b> — ${x.patient_name} — ${x.doctor||''} — ${x.status}</div>`).join('')||'لا توجد حجوزات اليوم'}catch(e){todayRows.textContent=e.message}}
async function loadBookings(){let d=await api('/api/admin/bookings');bookingRows.innerHTML=d.map(x=>`<div class="row"><b>${x.booking_number}</b> — ${x.patient_name} — ${x.phone}<br>${x.service||''} | ${x.doctor||''} | ${x.appointment_date} ${x.appointment_time}<select class="status" onchange="changeStatus('${x.booking_number}',this.value)"><option value="new" ${x.status==='new'?'selected':''}>جديد</option><option value="confirmed" ${x.status==='confirmed'?'selected':''}>مؤكد</option><option value="completed" ${x.status==='completed'?'selected':''}>مكتمل</option><option value="cancelled" ${x.status==='cancelled'?'selected':''}>ملغى</option></select><button onclick="printBooking('${x.booking_number}')">طباعة</button></div>`).join('')||'لا توجد حجوزات'}
async function changeStatus(id,status){await api('/api/admin/bookings/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify({status})});loadBookings()}
function printBooking(id){let w=window.open('','_blank');w.document.write('<html dir="rtl"><body style="font-family:Arial;padding:30px"><h2>مركز طب وجراحة الفم والأسنان بالزنتان</h2><p>رقم الحجز: '+id+'</p><p>يرجى مراجعة المركز حسب الموعد المسجل.</p><script>window.print()<\/script></body></html>')}
async function loadServices(){let d=await api('/api/admin/services');serviceRows.innerHTML=d.map(x=>`<div class="row"><b>${x.title}</b> — ${x.description}</div>`).join('')}
async function addService(){await api('/api/admin/services',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify({title:serviceTitle.value,description:serviceDesc.value})});serviceTitle.value='';serviceDesc.value='';loadServices()}
async function loadNews(){let d=await api('/api/admin/announcements');newsRows.innerHTML=d.map(x=>`<div class="row"><b>${x.title}</b><br>${x.body}</div>`).join('')}
async function addNews(){await api('/api/admin/announcements',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify({title:newsTitle.value,body:newsBody.value})});newsTitle.value='';newsBody.value='';loadNews()}
async function loadStats(){let d=await api('/api/admin/stats');let x=d[0]||{};year.value=x.year||'';root.value=x.root_canal||0;con.value=x.conservative||0;gum.value=x.gum||0;ext.value=x.extraction||0;opg.value=x.opg||0}
async function saveStats(){await api('/api/admin/stats/'+year.value,{method:'PUT',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify({root_canal:root.value,conservative:con.value,gum:gum.value,extraction:ext.value,opg:opg.value})});sm.textContent='تم حفظ الإحصائيات'}
function tab(x){for(const id of ['today','bookings','services','announcements','stats'])document.getElementById(id).hidden=id!==x}
async function logout(){await api('/api/auth/logout',{method:'POST',headers:{'x-csrf-token':csrf}});location.reload()}
